# Generated by Django 4.0.3 on 2022-04-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containercontent',
            old_name='heading',
            new_name='title',
        ),
    ]
