# Generated by Django 4.0.3 on 2022-04-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_heading_containercontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContainerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
