# Generated by Django 4.0.3 on 2022-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_contactcontainercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
